### ISSUE TITLE
Hot reload loses Endpoints

### ISSUE THREAD

**Issue by colinmollenhour** [skriptfabrik/elements-cli#2]
Thanks for sharing your work on this awesome tool!

I don't know if it is my particular file or what but when I edit a file the hot reload re-renders the page without the ENDPOINTS section, it's completely missing..  If I refresh the page the content is all there it is only when I trigger a hot-reload.

![image](https://user-images.githubusercontent.com/38738/174847852-307d03f2-5327-4c98-8089-bde7fb8f6c56.png)

Have you experienced this?

No errors are logged to stdout/stderr or to the browser console.

**Comment by schroedan** [comment]
That's strange. I haven't noticed it yet and will keep an eye on it.

**Comment by colinmollenhour** [comment]
I tried on some other OAS and it worked fine on them.. So might be related to the OAS but no idea why.. Perhaps there are error messages that are being suppressed or masked and could be exposed in the browser console or the server console?

**Comment by schroedan** [comment]
Currently, there is no bundled OAS validator from which to derive errors. The livereload module only reports to the browser when there are changes and reloads the whole page.

**Comment by schroedan** [comment]
The issue will be closed. If it occurs again, it can be reopened.
