### ISSUE TITLE
Don't update your npm package?

### ISSUE THREAD

**Issue by fuji44** [skriptfabrik/elements-cli#89]
First of all, thanks for creating such a useful tool.

Looking at the commits, it seems that you are updating the dependency packages in order, but npm package has not been pushed since last year.

If possible, I would like you to resume updating the npm package.

**Comment by MaSpeng** [comment]
@fuji44 we provided 2 new releases with the latest versions of the dependencies.

**Comment by fuji44** [comment]
Thank you! I'll use it.
